[features]
seeds = false
[programs.localnet]
solana_twitter = "AayjTawfdU2rH2QE36io7dtYPDeD9M4iNr1KJ2qTTFtT"

[programs.devnet]
solana_twitter = "AayjTawfdU2rH2QE36io7dtYPDeD9M4iNr1KJ2qTTFtT"

[programs.mainnet]
solana_twitter = "AayjTawfdU2rH2QE36io7dtYPDeD9M4iNr1KJ2qTTFtT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/henryksarat/.config/solana/twitter_id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"